# swiftmailer:
#     url: '%env(MAILER_URL)%'
#     spool: { type: 'memory' }
swiftmailer:
    transport: smtp
    host: smtp.gmail.com
    port: 587
    encryption: tls
    username: issamanel05@gmail.com
    password: fantachristine